// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { error, errorRequest, errorResponse } from '../../common/error';
import { bridgeGet, bridgeGetRequest, bridgeGetResponse } from '../../common/bridge-get';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getBridgeOkResponse = z.object({
  errors: z.array(error).optional(),
  data: z.array(bridgeGet).optional(),
});

/**
 *
 * @typedef  {GetBridgeOkResponse} getBridgeOkResponse
 * @property {Error[]}
 * @property {BridgeGet[]}
 */
export type GetBridgeOkResponse = z.infer<typeof getBridgeOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getBridgeOkResponseResponse = z
  .object({
    errors: z.array(errorResponse).optional(),
    data: z.array(bridgeGetResponse).optional(),
  })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getBridgeOkResponseRequest = z
  .object({ errors: z.array(errorRequest).nullish(), data: z.array(bridgeGetRequest).nullish() })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));
