// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const colorMode2 = z.enum(['color_temperature', 'color', 'previous']);

export type ColorMode2 = z.infer<typeof colorMode2>;
