// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { colorMode2 } from './color-mode-2';
import {
  colorColorTemperature2,
  colorColorTemperature2Request,
  colorColorTemperature2Response,
} from './color-color-temperature-2';

/**
 * The shape of the model inside the application code - what the users use
 */
export const dimmingColor2 = z.object({
  mode: colorMode2.optional(),
  colorTemperature1: colorColorTemperature2.optional(),
});

/**
 *
 * @typedef  {DimmingColor2} dimmingColor2
 * @property {ColorMode2} - State to activate after powerup. Availability of “color_temperature” and “color” modes depend on the capabilities of the lamp. Colortemperature will set the colortemperature to the specified value after power up. When setting color_temperature, the color_temperature property must be included Color will set the color tot he specified value after power up. When setting color mode, the color property must be included Previous will set color to the state it was in before powering off.
 * @property {ColorColorTemperature2}
 */
export type DimmingColor2 = z.infer<typeof dimmingColor2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const dimmingColor2Response = z
  .object({
    mode: colorMode2.optional(),
    color_temperature: colorColorTemperature2Response.optional(),
  })
  .transform((data) => ({
    mode: data['mode'],
    colorTemperature1: data['color_temperature'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const dimmingColor2Request = z
  .object({ mode: colorMode2.nullish(), colorTemperature1: colorColorTemperature2Request.nullish() })
  .transform((data) => ({
    mode: data['mode'],
    color_temperature: data['colorTemperature1'],
  }));
