// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { error, errorRequest, errorResponse } from '../../common/error';
import { lightGet, lightGetRequest, lightGetResponse } from '../../common/light-get';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getLightsOkResponse = z.object({
  errors: z.array(error).optional(),
  data: z.array(lightGet).optional(),
});

/**
 *
 * @typedef  {GetLightsOkResponse} getLightsOkResponse
 * @property {Error[]}
 * @property {LightGet[]}
 */
export type GetLightsOkResponse = z.infer<typeof getLightsOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getLightsOkResponseResponse = z
  .object({
    errors: z.array(errorResponse).optional(),
    data: z.array(lightGetResponse).optional(),
  })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getLightsOkResponseRequest = z
  .object({ errors: z.array(errorRequest).nullish(), data: z.array(lightGetRequest).nullish() })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));
