// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const powerupPreset2 = z.enum(['safety', 'powerfail', 'last_on_state', 'custom']);

export type PowerupPreset2 = z.infer<typeof powerupPreset2>;
