// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { dimmingMode2 } from './dimming-mode-2';
import { dimmingColor2, dimmingColor2Request, dimmingColor2Response } from './dimming-color-2';

/**
 * The shape of the model inside the application code - what the users use
 */
export const powerupDimming2 = z.object({
  mode: dimmingMode2.optional(),
  dimming: z.number().gte(0).lte(100).optional(),
  color: dimmingColor2.optional(),
});

/**
 * 
 * @typedef  {PowerupDimming2} powerupDimming2   
 * @property {DimmingMode2} - Dimming will set the brightness to the specified value after power up.
When setting mode “dimming”, the dimming property must be included.
Previous will set brightness to the state it was in before powering off.

 * @property {number} - Brightness percentage. value cannot be 0, writing 0 changes it to lowest possible brightness
 * @property {DimmingColor2} 
 */
export type PowerupDimming2 = z.infer<typeof powerupDimming2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const powerupDimming2Response = z
  .object({
    mode: dimmingMode2.optional(),
    dimming: z.number().gte(0).lte(100).optional(),
    color: dimmingColor2Response.optional(),
  })
  .transform((data) => ({
    mode: data['mode'],
    dimming: data['dimming'],
    color: data['color'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const powerupDimming2Request = z
  .object({ mode: dimmingMode2.nullish(), dimming: z.number().nullish(), color: dimmingColor2Request.nullish() })
  .transform((data) => ({
    mode: data['mode'],
    dimming: data['dimming'],
    color: data['color'],
  }));
