// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const batteryState = z.enum(['normal', 'low', 'critical']);

export type BatteryState = z.infer<typeof batteryState>;
