// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const dimmingDeltaAction = z.enum(['up', 'down', 'stop']);

export type DimmingDeltaAction = z.infer<typeof dimmingDeltaAction>;
