// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const dimmingMode1 = z.enum(['dimming', 'previous']);

export type DimmingMode1 = z.infer<typeof dimmingMode1>;
