// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const lightGetMode = z.enum(['normal', 'streaming']);

export type LightGetMode = z.infer<typeof lightGetMode>;
