// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const rtype = z.enum([
  'device',
  'bridge_home',
  'room',
  'zone',
  'light',
  'button',
  'relative_rotary',
  'temperature',
  'light_level',
  'motion',
  'camera_motion',
  'entertainment',
  'contact',
  'tamper',
  'grouped_light',
  'device_power',
  'zigbee_bridge_connectivity',
  'zigbee_connectivity',
  'zgp_connectivity',
  'bridge',
  'zigbee_device_discovery',
  'homekit',
  'matter',
  'matter_fabric',
  'scene',
  'entertainment_configuration',
  'public_image',
  'auth_v1',
  'behavior_script',
  'behavior_instance',
  'geofence',
  'geofence_client',
  'geolocation',
  'smart_scene',
]);

export type Rtype = z.infer<typeof rtype>;
