// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { supportedEffects } from './supported-effects';

/**
 * The shape of the model inside the application code - what the users use
 */
export const scenePaletteEffects = z.object({
  effect: supportedEffects.optional(),
});

/**
 *
 * @typedef  {ScenePaletteEffects} scenePaletteEffects
 * @property {SupportedEffects}
 */
export type ScenePaletteEffects = z.infer<typeof scenePaletteEffects>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scenePaletteEffectsResponse = z
  .object({
    effect: supportedEffects.optional(),
  })
  .transform((data) => ({
    effect: data['effect'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scenePaletteEffectsRequest = z.object({ effect: supportedEffects.nullish() }).transform((data) => ({
  effect: data['effect'],
}));
