// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const sensitivityStatus = z.enum(['set', 'changing']);

export type SensitivityStatus = z.infer<typeof sensitivityStatus>;
