// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const supportedDynamicStatus = z.enum(['dynamic_palette', 'none']);

export type SupportedDynamicStatus = z.infer<typeof supportedDynamicStatus>;
