// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const supportedEffects = z.enum(['prism', 'opal', 'glisten', 'sparkle', 'fire', 'candle', 'no_effect']);

export type SupportedEffects = z.infer<typeof supportedEffects>;
