// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { error, errorRequest, errorResponse } from '../../common/error';
import { roomGet, roomGetRequest, roomGetResponse } from '../../common/room-get';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getZonesOkResponse = z.object({
  errors: z.array(error).optional(),
  data: z.array(roomGet).optional(),
});

/**
 *
 * @typedef  {GetZonesOkResponse} getZonesOkResponse
 * @property {Error[]}
 * @property {RoomGet[]}
 */
export type GetZonesOkResponse = z.infer<typeof getZonesOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getZonesOkResponseResponse = z
  .object({
    errors: z.array(errorResponse).optional(),
    data: z.array(roomGetResponse).optional(),
  })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getZonesOkResponseRequest = z
  .object({ errors: z.array(errorRequest).nullish(), data: z.array(roomGetRequest).nullish() })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));
