// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const success = z.object({
  username: z.string().optional(),
  clientkey: z.string().optional(),
});

/**
 *
 * @typedef  {Success} success
 * @property {string}
 * @property {string}
 */
export type Success = z.infer<typeof success>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const successResponse = z
  .object({
    username: z.string().optional(),
    clientkey: z.string().optional(),
  })
  .transform((data) => ({
    username: data['username'],
    clientkey: data['clientkey'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const successRequest = z
  .object({ username: z.string().nullish(), clientkey: z.string().nullish() })
  .transform((data) => ({
    username: data['username'],
    clientkey: data['clientkey'],
  }));
