// This file was generated by liblab | https://liblab.com/

import { OpenHue } from 'open-hue';

(async () => {
  const openHue = new OpenHue({
    apiKey: 'YOUR_API_KEY',
  });

  const { data } = await openHue.resource.getResources();

  console.log(data);
})();
