// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { error, errorRequest, errorResponse } from '../../common/error';
import { motionGet, motionGetRequest, motionGetResponse } from '../../common/motion-get';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getMotionSensorOkResponse = z.object({
  errors: z.array(error).optional(),
  data: z.array(motionGet).optional(),
});

/**
 *
 * @typedef  {GetMotionSensorOkResponse} getMotionSensorOkResponse
 * @property {Error[]}
 * @property {MotionGet[]}
 */
export type GetMotionSensorOkResponse = z.infer<typeof getMotionSensorOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getMotionSensorOkResponseResponse = z
  .object({
    errors: z.array(errorResponse).optional(),
    data: z.array(motionGetResponse).optional(),
  })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getMotionSensorOkResponseRequest = z
  .object({ errors: z.array(errorRequest).nullish(), data: z.array(motionGetRequest).nullish() })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));
