// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import {
  GetBridgeHomeOkResponse,
  GetBridgeHomesOkResponse,
  getBridgeHomeOkResponseResponse,
  getBridgeHomesOkResponseResponse,
} from './models';

export class BridgeHomeService extends BaseService {
  /**
   * List all available bridge homes.
   * @returns {Promise<HttpResponse<GetBridgeHomesOkResponse>>} Bridge Home Success Response
   */
  async getBridgeHomes(requestConfig?: RequestConfig): Promise<HttpResponse<GetBridgeHomesOkResponse>> {
    const path = '/clip/v2/resource/bridge_home';
    const options: any = {
      responseSchema: getBridgeHomesOkResponseResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
   * Get details of a single bridge home from its given `{bridgeHomeId}`.
   * @param {string} bridgeHomeId - ID of the bridge home.
   * @returns {Promise<HttpResponse<GetBridgeHomeOkResponse>>} Bridge Home Success Response
   */
  async getBridgeHome(
    bridgeHomeId: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetBridgeHomeOkResponse>> {
    const path = this.client.buildPath('/clip/v2/resource/bridge_home/{bridgeHomeId}', { bridgeHomeId: bridgeHomeId });
    const options: any = {
      responseSchema: getBridgeHomeOkResponseResponse,
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
