// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { error, errorRequest, errorResponse } from '../../common/error';
import { lightLevelGet, lightLevelGetRequest, lightLevelGetResponse } from '../../common/light-level-get';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getLightLevelsOkResponse = z.object({
  errors: z.array(error).optional(),
  data: z.array(lightLevelGet).optional(),
});

/**
 *
 * @typedef  {GetLightLevelsOkResponse} getLightLevelsOkResponse
 * @property {Error[]}
 * @property {LightLevelGet[]}
 */
export type GetLightLevelsOkResponse = z.infer<typeof getLightLevelsOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getLightLevelsOkResponseResponse = z
  .object({
    errors: z.array(errorResponse).optional(),
    data: z.array(lightLevelGetResponse).optional(),
  })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getLightLevelsOkResponseRequest = z
  .object({ errors: z.array(errorRequest).nullish(), data: z.array(lightLevelGetRequest).nullish() })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));
