// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { error, errorRequest, errorResponse } from '../../common/error';
import { deviceGet, deviceGetRequest, deviceGetResponse } from '../../common/device-get';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getDeviceOkResponse = z.object({
  errors: z.array(error).optional(),
  data: z.array(deviceGet).optional(),
});

/**
 *
 * @typedef  {GetDeviceOkResponse} getDeviceOkResponse
 * @property {Error[]}
 * @property {DeviceGet[]}
 */
export type GetDeviceOkResponse = z.infer<typeof getDeviceOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getDeviceOkResponseResponse = z
  .object({
    errors: z.array(errorResponse).optional(),
    data: z.array(deviceGetResponse).optional(),
  })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getDeviceOkResponseRequest = z
  .object({ errors: z.array(errorRequest).nullish(), data: z.array(deviceGetRequest).nullish() })
  .transform((data) => ({
    errors: data['errors'],
    data: data['data'],
  }));
